disableRSS: false
enableRobotsTXT: true
Paginate: 8
rssLimit: 9
related:
  includeNewer: true
  threshold: 80
  toLower: false
  indices:
    - name: title
      weight: 30
    - name: description
      weight: 30
    - name: tags
      weight: 30
    - name: date
      weight: 10
minify:
  minifyOutput: true
outputs:
  section:
    - HTML
    - RSS
  home:
    - HTML
    - RSS
  page:
    - html
