googleAnalytics:
  anonymizeIP: true
  disable: false
  respectDoNotTrack: true
  useSessionStorage: true
  pygmentsCodeFences: true
  pygmentsStyle: native
twitter:
  disableInlineCSS: true
  simple: true
markup:
  highlight:
    hl_Lines: ""
    lineNoStart: 1
    lineNos: true
    tabWidth: 4
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
